import type { AtlasSeedData } from './types';

export const atlasSeedData: AtlasSeedData = {
  citations: [
    {
      id: 'cit-fire-ant-review-2007',
      title: 'The Fire Ants (Solenopsis) in Perspective',
      authors: ['W. R. Tschinkel'],
      publicationYear: 2006,
      publisher: 'Harvard University Press',
      sourceType: 'book',
    },
    {
      id: 'cit-cdc-fire-ant-stings',
      title: 'Imported Fire Ants',
      publisher: 'CDC',
      sourceType: 'government',
      url: 'https://www.cdc.gov/niosh/topics/fireants/default.html',
      accessedAt: '2026-07-23',
    },
    {
      id: 'cit-poison-control-fire-ant',
      title: 'Fire Ant Stings',
      publisher: 'Poison Control',
      sourceType: 'other',
      url: 'https://www.poison.org/articles/fire-ant-stings-201',
      accessedAt: '2026-07-23',
    },
    {
      id: 'cit-antwiki-sinvicta',
      title: 'Solenopsis invicta',
      publisher: 'AntWiki',
      sourceType: 'database',
      url: 'https://www.antwiki.org/wiki/Solenopsis_invicta',
      accessedAt: '2026-07-23',
    },
    {
      id: 'cit-editorial-placeholder',
      title: 'Editorial normalization for scaffold continuity',
      sourceType: 'other',
    },
  ],
  evidenceAssessments: [
    {
      id: 'ev-taxonomy',
      confidence: 'moderate',
      evidenceType: 'database',
      citationIds: ['cit-antwiki-sinvicta'],
    },
    {
      id: 'ev-delivery-sequence',
      confidence: 'moderate',
      evidenceType: 'review',
      notes: 'Delivery sequence is simplified schematic for educational purposes.',
      citationIds: ['cit-fire-ant-review-2007', 'cit-antwiki-sinvicta'],
    },
    {
      id: 'ev-venom-mixture',
      confidence: 'moderate',
      evidenceType: 'review',
      citationIds: ['cit-fire-ant-review-2007'],
    },
    {
      id: 'ev-solenopsin-feature',
      confidence: 'low',
      evidenceType: 'editorial_normalization',
      notes:
        'Solenopsin A is featured for scaffold demonstration. Quantitation and precise composition pending sourcing.',
      citationIds: ['cit-editorial-placeholder'],
    },
    {
      id: 'ev-local-clinical',
      confidence: 'moderate',
      evidenceType: 'clinical',
      citationIds: ['cit-poison-control-fire-ant', 'cit-cdc-fire-ant-stings'],
    },
    {
      id: 'ev-systemic-allergy',
      confidence: 'moderate',
      evidenceType: 'clinical',
      notes: 'Systemic allergic reactions are possible but not universal outcomes.',
      citationIds: ['cit-poison-control-fire-ant', 'cit-cdc-fire-ant-stings'],
    },
    {
      id: 'ev-geography-pending',
      confidence: 'unknown',
      evidenceType: 'editorial_normalization',
      notes: 'Validated range geometry files are pending curation.',
      citationIds: ['cit-editorial-placeholder'],
    },
  ],
  taxonomy: [
    {
      id: 'tax-sinvicta',
      organismId: 'org-solenopsis-invicta',
      kingdom: 'Animalia',
      phylum: 'Arthropoda',
      className: 'Insecta',
      order: 'Hymenoptera',
      family: 'Formicidae',
      genus: 'Solenopsis',
      species: 'Solenopsis invicta',
    },
  ],
  organisms: [
    {
      id: 'org-solenopsis-invicta',
      scientificName: 'Solenopsis invicta',
      commonName: 'Red imported fire ant',
      toxicStrategy: 'venomous',
      overview:
        'Solenopsis invicta is an ant species widely studied for defensive sting behavior, rapid colony recruitment, and ecological impact where established.',
      naturalHistory: [
        'Workers can rapidly recruit nestmates when disturbed.',
        'Colonies occupy disturbed soils, lawns, fields, and urban interfaces.',
        'Defensive behavior commonly involves grip-and-sting sequences.',
      ],
      taxonomyId: 'tax-sinvicta',
      deliveryMechanismId: 'deliv-fire-ant-sting',
      evidence: {
        id: 'ev-taxonomy',
        confidence: 'moderate',
        evidenceType: 'database',
        citationIds: ['cit-antwiki-sinvicta'],
      },
    },
  ],
  deliveryMechanisms: [
    {
      id: 'deliv-fire-ant-sting',
      organismId: 'org-solenopsis-invicta',
      route: 'sting',
      summary: 'Mandibles anchor while the abdomen rotates to place the stinger and inject venom.',
      sequence: [
        'Mandibles grip skin or substrate.',
        'Abdomen rotates under the body axis.',
        'Stinger penetrates tissue.',
        'Venom is injected into local tissue.',
      ],
      evidence: {
        id: 'ev-delivery-sequence',
        confidence: 'moderate',
        evidenceType: 'review',
        citationIds: ['cit-fire-ant-review-2007', 'cit-antwiki-sinvicta'],
      },
    },
  ],
  biologicalMaterials: [
    {
      id: 'bio-fire-ant-venom',
      organismId: 'org-solenopsis-invicta',
      kind: 'venom',
      name: 'Fire-ant venom',
      description: 'A venomous secretion associated with sting delivery.',
      evidence: {
        id: 'ev-venom-mixture',
        confidence: 'moderate',
        evidenceType: 'review',
        citationIds: ['cit-fire-ant-review-2007'],
      },
    },
  ],
  toxicMaterials: [
    {
      id: 'ven-fire-ant-primary',
      organismId: 'org-solenopsis-invicta',
      biologicalMaterialId: 'bio-fire-ant-venom',
      name: 'Solenopsis invicta venom',
      description:
        'A biologically active mixture with alkaloid-rich components and protein fractions relevant to allergic responses.',
      ecologicalRoleSummary:
        'Likely supports defense, prey subduing, and competitive ecological interactions.',
      materialKind: 'venom',
      evidence: {
        id: 'ev-venom-mixture',
        confidence: 'moderate',
        evidenceType: 'review',
        citationIds: ['cit-fire-ant-review-2007'],
      },
    },
  ],
  toxins: [
    {
      id: 'tox-solenopsin-a',
      toxicMaterialId: 'ven-fire-ant-primary',
      displayName: 'Solenopsin A',
      family: 'Piperidine alkaloids (solenopsins)',
      notes:
        'Featured representative compound. Not claimed as sole mediator of all clinical effects.',
      evidence: {
        id: 'ev-solenopsin-feature',
        confidence: 'low',
        evidenceType: 'editorial_normalization',
        citationIds: ['cit-editorial-placeholder'],
      },
    },
  ],
  toxinComponents: [
    {
      id: 'comp-alkaloids',
      toxicMaterialId: 'ven-fire-ant-primary',
      componentCategory: 'Piperidine alkaloids',
      abundanceQualifier: 'not_quantified',
      summary: 'Qualitatively prominent class in many fire-ant venom descriptions.',
      evidence: {
        id: 'ev-venom-mixture',
        confidence: 'moderate',
        evidenceType: 'review',
        citationIds: ['cit-fire-ant-review-2007'],
      },
    },
    {
      id: 'comp-proteins',
      toxicMaterialId: 'ven-fire-ant-primary',
      componentCategory: 'Protein fractions/allergens',
      abundanceQualifier: 'not_quantified',
      summary: 'Associated with immune-mediated responses in sensitized individuals.',
      evidence: {
        id: 'ev-systemic-allergy',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant', 'cit-cdc-fire-ant-stings'],
      },
    },
  ],
  molecularEntities: [
    {
      id: 'mol-solenopsin-a',
      toxinId: 'tox-solenopsin-a',
      displayName: 'Solenopsin A',
      molecularClass: 'small_molecule',
      formula: null,
      molecularWeight: null,
      structureDataSource: null,
      evidence: {
        id: 'ev-solenopsin-feature',
        confidence: 'low',
        evidenceType: 'editorial_normalization',
        citationIds: ['cit-editorial-placeholder'],
      },
    },
  ],
  molecularStructureAssets: [
    {
      id: 'asset-mol3d-solenopsin-a',
      molecularEntityId: 'mol-solenopsin-a',
      format: 'sdf',
      localPath: '/structures/solenopsin-a.sdf',
      verified: false,
    },
    {
      id: 'asset-mol2d-solenopsin-a',
      molecularEntityId: 'mol-solenopsin-a',
      format: 'svg',
      localPath: '/images/solenopsin-a-2d.svg',
      verified: false,
    },
  ],
  molecularTargets: [
    {
      id: 'target-local-cell-membrane-process',
      toxinId: 'tox-solenopsin-a',
      targetName: 'Local tissue and cell-response processes',
      targetType: 'unknown',
      summary:
        'Specific primary molecular targets are represented conservatively as unresolved in this seed.',
      evidence: {
        id: 'ev-solenopsin-feature',
        confidence: 'low',
        evidenceType: 'editorial_normalization',
        citationIds: ['cit-editorial-placeholder'],
      },
    },
  ],
  mechanismSteps: [
    {
      id: 'mech-1-exposure',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      order: 1,
      level: 'exposure',
      title: 'Sting exposure',
      description: 'Ant anchors with mandibles and delivers venom through the stinger.',
      evidence: {
        id: 'ev-delivery-sequence',
        confidence: 'moderate',
        evidenceType: 'review',
        citationIds: ['cit-fire-ant-review-2007', 'cit-antwiki-sinvicta'],
      },
    },
    {
      id: 'mech-2-tissue-deposition',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      order: 2,
      level: 'tissue',
      title: 'Local venom deposition',
      description: 'Venom components are deposited in superficial tissue at sting sites.',
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'mech-3-immediate-pain',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      order: 3,
      level: 'clinical',
      title: 'Immediate pain and burning sensation',
      description: 'Many sting events produce rapid local pain or burning sensation.',
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant', 'cit-cdc-fire-ant-stings'],
      },
    },
    {
      id: 'mech-4-inflammatory-local',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      order: 4,
      level: 'tissue',
      title: 'Local inflammatory response',
      description: 'Inflammatory and immune processes contribute to visible local lesions.',
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'mech-5-lesion-outcome',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      order: 5,
      level: 'clinical',
      title: 'Wheal/pustule development where applicable',
      description:
        'A local lesion can develop over time; presentation varies by individual and exposure.',
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'mech-6-persistent-discomfort',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      order: 6,
      level: 'clinical',
      title: 'Persistent local discomfort in some cases',
      description:
        'Some individuals report prolonged local discomfort after initial sting effects.',
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-cdc-fire-ant-stings'],
      },
    },
  ],
  anatomicalSystems: [
    {
      id: 'anat-skin',
      name: 'Skin',
      description: 'Primary local site of venom deposition and lesion development.',
    },
    {
      id: 'anat-peripheral-nerves',
      name: 'Peripheral sensory nerves',
      description: 'Supports local pain and burning perception.',
    },
    {
      id: 'anat-circulatory',
      name: 'Circulatory system',
      description: 'Potential systemic involvement context.',
    },
    {
      id: 'anat-respiratory',
      name: 'Respiratory system',
      description: 'Relevant in severe allergic responses.',
    },
    {
      id: 'anat-immune',
      name: 'Immune/inflammatory response',
      description: 'Mediator of local and allergic reaction pathways.',
    },
  ],
  symptoms: [
    {
      id: 'sym-pain',
      name: 'Pain/Burning',
      description: 'Rapid local pain sensation after sting.',
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'sym-local-lesion',
      name: 'Local wheal/pustule or lesion',
      description: 'Localized lesion response that may evolve after sting.',
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'sym-systemic-allergy',
      name: 'Systemic allergic reaction (possible pathway)',
      description: 'Potential severe allergic response in sensitized individuals.',
      evidence: {
        id: 'ev-systemic-allergy',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant', 'cit-cdc-fire-ant-stings'],
      },
    },
  ],
  physiologicalEffects: [
    {
      id: 'phys-local-skin',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      anatomicalSystemId: 'anat-skin',
      symptomId: 'sym-local-lesion',
      pathwayType: 'direct_venom',
      title: 'Local skin tissue impact',
      description: 'Direct local tissue effects at sting site.',
      order: 1,
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'phys-local-nerves',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      anatomicalSystemId: 'anat-peripheral-nerves',
      symptomId: 'sym-pain',
      pathwayType: 'direct_venom',
      title: 'Sensory nerve-associated pain',
      description: 'Local pain and burning sensations are commonly reported.',
      order: 2,
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'phys-inflammatory',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      anatomicalSystemId: 'anat-immune',
      symptomId: 'sym-local-lesion',
      pathwayType: 'inflammatory_immune',
      title: 'Local inflammatory response',
      description: 'Inflammatory response contributes to evolving lesion patterns.',
      order: 3,
      evidence: {
        id: 'ev-local-clinical',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant'],
      },
    },
    {
      id: 'phys-systemic-allergy',
      subject: { kind: 'organism_exposure', slug: 'solenopsis-invicta' },
      anatomicalSystemId: 'anat-respiratory',
      symptomId: 'sym-systemic-allergy',
      pathwayType: 'systemic_allergic',
      title: 'Systemic allergic pathway (non-default)',
      description: 'A separate pathway representing possible allergic systemic reactions.',
      order: 4,
      evidence: {
        id: 'ev-systemic-allergy',
        confidence: 'moderate',
        evidenceType: 'clinical',
        citationIds: ['cit-poison-control-fire-ant', 'cit-cdc-fire-ant-stings'],
      },
    },
  ],
  geographicRanges: [
    {
      id: 'geo-native-range',
      organismId: 'org-solenopsis-invicta',
      layerType: 'native_range',
      summary: 'Native range geometry not yet bundled; source-backed geometry pending.',
      evidence: {
        id: 'ev-geography-pending',
        confidence: 'unknown',
        evidenceType: 'editorial_normalization',
        citationIds: ['cit-editorial-placeholder'],
      },
    },
    {
      id: 'geo-introduced-range',
      organismId: 'org-solenopsis-invicta',
      layerType: 'introduced_range',
      summary: 'Introduced range geometry not yet bundled; source-backed geometry pending.',
      evidence: {
        id: 'ev-geography-pending',
        confidence: 'unknown',
        evidenceType: 'editorial_normalization',
        citationIds: ['cit-editorial-placeholder'],
      },
    },
  ],
  habitats: [
    {
      id: 'hab-disturbed-soils',
      organismId: 'org-solenopsis-invicta',
      name: 'Disturbed soils and anthropogenic landscapes',
      summary: 'Often established in open disturbed habitats, lawns, and managed landscapes.',
      evidence: {
        id: 'ev-taxonomy',
        confidence: 'moderate',
        evidenceType: 'database',
        citationIds: ['cit-antwiki-sinvicta'],
      },
    },
  ],
  ecologicalRoles: [
    {
      id: 'eco-defense',
      organismId: 'org-solenopsis-invicta',
      role: 'Defense and competitive interactions',
      summary:
        'Venom-associated sting behavior is relevant to defense and interference competition.',
      evidence: {
        id: 'ev-venom-mixture',
        confidence: 'moderate',
        evidenceType: 'review',
        citationIds: ['cit-fire-ant-review-2007'],
      },
    },
  ],
  mediaAssets: [
    {
      id: 'media-organism-photo-placeholder',
      kind: 'organism_photo',
      localPath: '/images/organism-photo-placeholder.txt',
      attributionText: 'Placeholder only. Production image pending license verification.',
      redistributionVerified: false,
    },
    {
      id: 'media-mandibles-placeholder',
      kind: 'anatomical_photo',
      localPath: '/images/mandibles-placeholder.txt',
      attributionText: 'Placeholder only. Close-up source pending.',
      redistributionVerified: false,
    },
    {
      id: 'media-stinger-placeholder',
      kind: 'anatomical_photo',
      localPath: '/images/stinger-placeholder.txt',
      attributionText: 'Placeholder only. Close-up source pending.',
      redistributionVerified: false,
    },
    {
      id: 'media-habitat-placeholder',
      kind: 'organism_photo',
      localPath: '/images/habitat-placeholder.txt',
      attributionText: 'Placeholder only. Habitat image pending source verification.',
      redistributionVerified: false,
    },
    {
      id: 'media-2d-solenopsin-placeholder',
      kind: 'molecular_2d',
      localPath: '/images/solenopsin-a-2d.svg',
      attributionText: 'Placeholder marker. Scientifically sourced 2D structure pending.',
      redistributionVerified: false,
    },
    {
      id: 'media-3d-solenopsin-placeholder',
      kind: 'molecular_3d',
      localPath: '/structures/solenopsin-a.sdf',
      attributionText: 'Placeholder marker. Verified 3D structure file pending.',
      redistributionVerified: false,
    },
    {
      id: 'media-range-geometry-placeholder',
      kind: 'range_geometry',
      localPath: '/geography/solenopsis-invicta-range.geojson',
      attributionText: 'Placeholder marker. Source-backed geometry pending.',
      redistributionVerified: false,
    },
  ],
};
